// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ExamsPaltFormDbContext))]
    [Migration("20251026213902_AddNotification")]
    partial class AddNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "2fc215ad-e1e4-4aa7-93c2-25daa1a22694",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "f7190d75-f769-4a43-84ce-52bfe9656cb4",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "00250a98-3301-460d-954b-660fa0e3d1d2",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "cc2eb532-864e-4d04-b31a-3eba8288b574",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Models.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Computer Science / IT"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Biology"
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "History"
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Geography"
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Literature / Language Arts"
                        });
                });

            modelBuilder.Entity("Models.Model.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Models.Model.ExamQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId", "ExamId");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamQuestions");
                });

            modelBuilder.Entity("Models.Model.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Models.Model.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 7,
                            CorrectAnswer = "Paris",
                            Difficulty = "Easy",
                            Options = "[\"Paris\",\"London\",\"Rome\",\"Berlin\"]",
                            QuestionName = "Capital Cities",
                            QuestionText = "What is the capital of France?",
                            Score = 5.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CorrectAnswer = "Oxygen",
                            Difficulty = "Med",
                            Options = "[\"Oxygen\",\"Gold\",\"Hydrogen\",\"Iron\"]",
                            QuestionName = "Chemistry Basics",
                            QuestionText = "Which element has the chemical symbol 'O'?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CorrectAnswer = "Mars",
                            Difficulty = "Hard",
                            Options = "[\"Mars\",\"Venus\",\"Jupiter\",\"Saturn\"]",
                            QuestionName = "Astronomy",
                            QuestionText = "Which planet is known as the Red Planet?",
                            Score = 4.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CorrectAnswer = "First Law",
                            Difficulty = "Easy",
                            Options = "[\"First Law\",\"Second Law\",\"Third Law\",\"Law of Gravity\"]",
                            QuestionName = "Newton's First Law",
                            QuestionText = "An object in motion stays in motion unless acted upon by an external force. Which law is this?",
                            Score = 5.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CorrectAnswer = "m/s²",
                            Difficulty = "Easy",
                            Options = "[\"m/s\\u00B2\",\"m/s\",\"N\",\"kg\"]",
                            QuestionName = "Acceleration Unit",
                            QuestionText = "What is the SI unit of acceleration?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CorrectAnswer = "Acceleration",
                            Difficulty = "Medium",
                            Options = "[\"Acceleration\",\"Velocity\",\"Time\",\"Energy\"]",
                            QuestionName = "Force Calculation",
                            QuestionText = "Force equals mass times what?",
                            Score = 4.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CorrectAnswer = "Gravitational",
                            Difficulty = "Medium",
                            Options = "[\"Electromagnetic\",\"Gravitational\",\"Nuclear\",\"Friction\"]",
                            QuestionName = "Gravitational Force",
                            QuestionText = "Which force keeps planets in orbit?",
                            Score = 4.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CorrectAnswer = "Kinetic",
                            Difficulty = "Easy",
                            Options = "[\"Potential\",\"Kinetic\",\"Thermal\",\"Chemical\"]",
                            QuestionName = "Kinetic Energy",
                            QuestionText = "Which energy does a moving object have?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CorrectAnswer = "Distance",
                            Difficulty = "Medium",
                            Options = "[\"Time\",\"Distance\",\"Mass\",\"Speed\"]",
                            QuestionName = "Work Concept",
                            QuestionText = "Work is done when a force is applied over what?",
                            Score = 4.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CorrectAnswer = "Velocity",
                            Difficulty = "Medium",
                            Options = "[\"Velocity\",\"Acceleration\",\"Force\",\"Energy\"]",
                            QuestionName = "Momentum",
                            QuestionText = "Momentum equals mass times what?",
                            Score = 4.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CorrectAnswer = "Ohm's Law",
                            Difficulty = "Hard",
                            Options = "[\"Ohm\\u0027s Law\",\"Newton\\u0027s Law\",\"Faraday\\u0027s Law\",\"Hooke\\u0027s Law\"]",
                            QuestionName = "Ohm's Law",
                            QuestionText = "Voltage equals current times resistance. This is which law?",
                            Score = 5.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CorrectAnswer = "Refraction",
                            Difficulty = "Easy",
                            Options = "[\"Reflection\",\"Refraction\",\"Diffraction\",\"Absorption\"]",
                            QuestionName = "Refraction",
                            QuestionText = "Bending of light when passing from one medium to another is called?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            CorrectAnswer = "Hertz",
                            Difficulty = "Easy",
                            Options = "[\"Hertz\",\"Newton\",\"Joule\",\"Meter\"]",
                            QuestionName = "Frequency Unit",
                            QuestionText = "What is the unit of frequency?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 8,
                            CorrectAnswer = "Shakespeare",
                            Difficulty = "Easy",
                            Options = "[\"Shakespeare\",\"Hemingway\",\"Dickens\",\"Austen\"]",
                            QuestionName = "Literature",
                            QuestionText = "Who wrote 'Romeo and Juliet'?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CorrectAnswer = "Mitochondria",
                            Difficulty = "Easy",
                            Options = "[\"Nucleus\",\"Mitochondria\",\"Ribosome\",\"Chloroplast\"]",
                            QuestionName = "Cell Biology",
                            QuestionText = "What is the powerhouse of the cell?",
                            Score = 4.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CorrectAnswer = "1945",
                            Difficulty = "Medium",
                            Options = "[\"1940\",\"1945\",\"1950\",\"1939\"]",
                            QuestionName = "History",
                            QuestionText = "Which year did World War II end?",
                            Score = 5.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CorrectAnswer = "Au",
                            Difficulty = "Easy",
                            Options = "[\"Au\",\"Ag\",\"Fe\",\"Go\"]",
                            QuestionName = "Chemistry",
                            QuestionText = "What is the chemical symbol for gold?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            CorrectAnswer = "Jupiter",
                            Difficulty = "Medium",
                            Options = "[\"Earth\",\"Jupiter\",\"Saturn\",\"Mars\"]",
                            QuestionName = "Astronomy",
                            QuestionText = "What is the largest planet in the solar system?",
                            Score = 4.0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CorrectAnswer = "HTML",
                            Difficulty = "Easy",
                            Options = "[\"C#\",\"Python\",\"HTML\",\"Java\"]",
                            QuestionName = "Programming",
                            QuestionText = "Which language is used for web development?",
                            Score = 3.0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CorrectAnswer = "Africa",
                            Difficulty = "Medium",
                            Options = "[\"Africa\",\"Asia\",\"Europe\",\"Australia\"]",
                            QuestionName = "Geography",
                            QuestionText = "Which continent is known as the 'Dark Continent'?",
                            Score = 4.0
                        });
                });

            modelBuilder.Entity("Models.Model.StudentAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentExamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentExamId");

                    b.ToTable("StudentAnswers");
                });

            modelBuilder.Entity("Models.Model.StudentExam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ExamId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ExamId");

                    b.ToTable("StudentExams");
                });

            modelBuilder.Entity("Models.Model.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "cc2eb532-864e-4d04-b31a-3eba8288b574",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d6d1edbf-dcb4-48b2-b22d-dc20d365de79",
                            Email = "ryanabwryan34@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "RYANABWRYAN34@GMAIL.COM",
                            NormalizedUserName = "RYYAN2001",
                            PasswordHash = "AQAAAAIAAYagAAAAECenvy/0Lui/b1i/TdeypRdcHtJamNOKT0eynQpTX6vhsCMQBP9GbPo/l42lutlo7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "817c9768-f570-4727-be92-dc8614e67307",
                            TwoFactorEnabled = false,
                            UserName = "ryyan2001",
                            FullName = "Ryyan Abo Ryyan"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Model.Exam", b =>
                {
                    b.HasOne("Models.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Models.Model.ExamQuestion", b =>
                {
                    b.HasOne("Models.Model.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Model.Question", "Question")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Models.Model.Notification", b =>
                {
                    b.HasOne("Models.Model.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Models.Model.Question", b =>
                {
                    b.HasOne("Models.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Models.Model.StudentAnswer", b =>
                {
                    b.HasOne("Models.Model.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Model.StudentExam", "StudentExam")
                        .WithMany()
                        .HasForeignKey("StudentExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("StudentExam");
                });

            modelBuilder.Entity("Models.Model.StudentExam", b =>
                {
                    b.HasOne("Models.Model.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Model.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Models.Model.Exam", b =>
                {
                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("Models.Model.Question", b =>
                {
                    b.Navigation("ExamQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
